//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowHistories
    {
        public int BorrowHistoryId { get; set; }
        public int BookId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime BorrowDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
